services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    container_name: ayser-backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    environment:
      - APP_ENV=dev
    volumes:
      - ../backend/app:/app/app
      - ../backend/.env:/app/.env
    networks:
      - ayser-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    container_name: ayser-frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/static:/app/static
      - ../frontend/svelte.config.js:/app/svelte.config.js
      - ../frontend/tsconfig.json:/app/tsconfig.json
      - ../frontend/vite.config.ts:/app/vite.config.ts
    networks:
      - ayser-network
networks:
  ayser-network:
    driver: bridge
